#!/usr/bin/env bash
#
# corpus/lint.sh — health check for the ebook-reader corpus (see CLAUDE.md).
#
#   bash corpus/lint.sh          # check: frontmatter, links, page size; exit != 0 on failure
#   bash corpus/lint.sh --index  # regenerate the wiki catalog block in index.md
#
# Checks every wiki/*.md has `summary:` + `updated:` frontmatter, that every
# relative markdown link resolves on disk, and that no page's BODY (frontmatter
# excluded) exceeds ~200 lines. Mechanical only — the human sweep for stale
# claims / contradictions still lives in the skill's §7.

set -uo pipefail

CORPUS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WIKI_DIR="$CORPUS_DIR/wiki"
INDEX="$CORPUS_DIR/index.md"
MAX_BODY_LINES=200

# --- helpers ----------------------------------------------------------------

# Print the frontmatter value for a key ("" if absent). Reads only the leading
# `---`…`---` block.
frontmatter_value() {
  awk -v key="$1:" '
    NR==1 && $0!="---" { exit }
    NR==1 { infm=1; next }
    infm && $0=="---" { exit }
    infm && index($0, key)==1 {
      sub("^" key "[ \t]*", ""); print; exit
    }
  ' "$2"
}

# Count body lines = total minus the leading frontmatter block (if any).
body_line_count() {
  awk '
    NR==1 && $0=="---" { infm=1; next }
    infm && $0=="---" { infm=0; next }
    infm { next }
    { n++ }
    END { print n+0 }
  ' "$1"
}

# --- --index: regenerate the wiki catalog block -----------------------------

if [[ "${1:-}" == "--index" ]]; then
  BEGIN="<!-- BEGIN wiki-catalog (generated by lint.sh --index) -->"
  END="<!-- END wiki-catalog -->"
  if ! grep -qF "$BEGIN" "$INDEX" || ! grep -qF "$END" "$INDEX"; then
    echo "lint: index.md is missing the '$BEGIN' / '$END' markers; add them where the wiki catalog should go." >&2
    exit 1
  fi
  tmp="$(mktemp)"
  {
    echo "$BEGIN"
    for f in "$WIKI_DIR"/*.md; do
      base="$(basename "$f")"
      summary="$(frontmatter_value summary "$f")"
      [[ -z "$summary" ]] && summary="(no summary — add frontmatter)"
      echo "- [$base](wiki/$base) — $summary"
    done
    echo "$END"
  } > "$tmp"
  # Splice the generated block in place of the old one.
  awk -v beginm="$BEGIN" -v endm="$END" -v block="$tmp" '
    $0==beginm { inblk=1; while((getline line < block) > 0) print line; close(block); next }
    $0==endm { inblk=0; next }
    !inblk { print }
  ' "$INDEX" > "$INDEX.new" && mv "$INDEX.new" "$INDEX"
  rm -f "$tmp"
  echo "lint: regenerated wiki catalog in index.md ($(ls "$WIKI_DIR"/*.md | wc -l | tr -d ' ') pages)."
  exit 0
fi

# --- check mode -------------------------------------------------------------

fail=0
err() { echo "lint: $1" >&2; fail=1; }

# 1) Frontmatter + 2) body size, per wiki page.
for f in "$WIKI_DIR"/*.md; do
  rel="wiki/$(basename "$f")"
  [[ -z "$(frontmatter_value summary "$f")" ]] && err "$rel: missing 'summary:' frontmatter"
  [[ -z "$(frontmatter_value updated "$f")" ]] && err "$rel: missing 'updated:' frontmatter"
  n="$(body_line_count "$f")"
  (( n > MAX_BODY_LINES )) && err "$rel: body is $n lines (> $MAX_BODY_LINES) — split it (one concept per file)"
done

# 3) Relative links resolve, across the whole corpus.
while IFS= read -r f; do
  dir="$(dirname "$f")"
  # Pull every ](target) markdown link target.
  grep -oE '\]\([^)]+\)' "$f" 2>/dev/null | sed -E 's/^\]\(//; s/\)$//' | while IFS= read -r target; do
    # Skip URLs, mail, and pure in-page anchors.
    case "$target" in
      http://*|https://*|mailto:*|\#*) continue ;;
    esac
    path="${target%%#*}"          # strip #anchor
    [[ -z "$path" ]] && continue
    if [[ ! -e "$dir/$path" ]]; then
      echo "lint: $(basename "$f"): broken relative link -> $target" >&2
      echo "BROKEN" >> "$CORPUS_DIR/.lint-broken"
    fi
  done
done < <(find "$CORPUS_DIR" -name '*.md')

if [[ -f "$CORPUS_DIR/.lint-broken" ]]; then
  fail=1
  rm -f "$CORPUS_DIR/.lint-broken"
fi

if (( fail )); then
  echo "lint: FAILED" >&2
  exit 1
fi
echo "lint: OK — wiki frontmatter, link resolution, and page sizes all pass."
